name: Build NixOS Netboot and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build Netboot
      run: |
        nix-build '<nixpkgs/nixos/release.nix>' \
        -A netboot.x86_64-linux \
        --arg configuration ./configuration.nix

    - name: Prepare Release Files
      run: |
        mkdir -p release
        # Find files in the Nix build output symlink
        cp result/netboot/netboot.ipxe" release/netboot.ipxe
        cp "$(readlink -f result/netboot)/bzImage" release/bzImage
        cp "$(readlink -f result/netboot)/initrd" release/initrd.img
        cd release
        zip -r ../nixos-disk-destroyer.zip *

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: nixos-disk-destroyer.zip
        tag_name: v${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
